# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: fastlane ios beta gtoken:"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" faasp:"myci-nrzc-gwlj-nvwi" aei:"raul.quispe@icloud.com" fpass:"olokb7i88R@" mpass:"oloRkb7i@" fuser:"raul.quispe@icloud.com" fteamid:"73A3QCVC2H" fitcteamid:"675131" appidr:"com.wallets.cencopay.dev"