# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Force Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
      # - name: Sync Certificates
      #   run: fastlane ios certificates gtoken:${{ secrets.G_TOKEN }} appidr:"com.wallets.cencopay.dev" fpass:"olokb7i88R@" mpass:"oloRkb7i@"
      # - name: Read Certificate
      #   run: security find-certificate -a -c 'Apple Worldwide Developer Relations' -p /Users/runner/Library/Keychains/fastlane_tmp_keychain-db
      - name: Build App
        run: fastlane ios beta gtoken:${{ secrets.G_TOKEN }} faasp:"myci-nrzc-gwlj-nvwi" aei:"raul.quispe@icloud.com" fpass:"olokb7i88R@" mpass:"oloRkb7i@" fuser:"raul.quispe@icloud.com" fteamid:"73A3QCVC2H" fitcteamid:"675131" appidr:"com.wallets.cencopay.dev"      # - name: Read Log
      #   run: echo /Users/runner/Library/Logs/gym/iOSBitrise-CencoPay-Production.log